#!/usr/bin/env python3
import sys
from pathlib import Path


def notice():
    print("Command Error.\nUsage:\n  show c      Show Conditions\n  show w      Show No Warranty")
    raise SystemExit(1)


def showc(license_lines):
    active = False
    for line in license_lines:
        if line.startswith("  2."):
            active = True
            print("\n")
            print("                             Conditions:")
        if active and line.startswith("    "):
            if line[4:7] in ["a) ", "b) ", "c) "]:
                print("\n")
            print(line[4:].rstrip(), end=" ")
        if line.startswith("  3."):
            active = False


def showw(license_lines):
    active = False
    for line in license_lines:
        if line.rstrip().endswith("NO WARRANTY"):
            active = True
            print("\n")
        if line.rstrip().endswith("END OF TERMS AND CONDITIONS"):
            active = False
        if active:
            if line.startswith("  11. ") or line.startswith("  12. "):
                line = line[:2] + line[3:]
                print("\n")
            print(line.rstrip(), end=" ")


def main():
    if len(sys.argv) != 2:
        notice()

    license_lines = Path("LICENSE").read_text().splitlines()
    option = sys.argv[1].lower()
    if option == "c":
        showc(license_lines)
    elif option == "w":
        showw(license_lines)
    else:
        notice()


if __name__ == "__main__":
    main()
