#!/bin/sh
#**********************************************************************
#* Filename    : start
#* Description : a simple bash script to run the django server
#* Author      : Cavon
#* Brand       : SunFounder
#* E-mail      : service@sunfounder.com
#* Website     : www.sunfounder.com
#* Update      : Cavon    2016-09-13    New release
#*               Cavon    2016-10-19    Add install config
#**********************************************************************

if [ "$1" = "" ]
then
	# Run server listen to any IP address and port 8000
	echo "Server running"
	if [ -x ../venv/bin/python ]; then
		../venv/bin/python manage.py runserver 0.0.0.0:8000
	else
		python3 manage.py runserver 0.0.0.0:8000
	fi
elif [ "$1" = "install" ]
then
	echo 'Running servo installation'
	if [ -x ../venv/bin/picar ]; then
		../venv/bin/picar servo-install
	elif command -v picar >/dev/null 2>&1; then
		picar servo-install
	else
		echo 'picar command not found. Run ../install_dependencies first.'
		exit 1
	fi
fi
